### ISSUE TITLE
Inquiry about Project Dependencies

### ISSUE THREAD

**Issue by xwqtju** [Qualcomm-AI-research/geometric-algebra-transformer#1]
Hi,
I could not find a detailed list of dependencies in the project documentation. Could you please provide this information or guide me to where I might find it? This is very important to me and will help me better understand and utilize your project.

Thank you very much for your time and assistance.

Best regards,

**Comment by johannbrehmer** [comment]
Hi,

apologies for seeing this so late.

We specify our dependencies in the [Dockerfile](https://github.com/Qualcomm-AI-research/geometric-algebra-transformer/blob/a6fd8a85406a7c35f274ca00b1bc1b1a396c17a6/docker/Dockerfile). You can find instructions how to use it in [section 2 in the README](https://github.com/Qualcomm-AI-research/geometric-algebra-transformer/blob/a6fd8a85406a7c35f274ca00b1bc1b1a396c17a6/README.md#2-getting-started). If you prefer not to use Docker, you can alternatively reproduce the installation steps contained in the Dockerfile in your own environment. 

Does that help? Please let me know if you have further questions.

**Comment by ZXP-S-works** [comment]
Hi Johann,

Thanks for the great work!

I am trying to install GATr without docker as well. However, when I run "python3 /docker/ext_packages/install_upstream_python_packages.py", I got error

```
INFO:transformers.file_utils:PyTorch version 2.0.1 available.
DEBUG:transformers.file_utils:Successfully imported torch-scatter version 2.1.2
Traceback (most recent call last):
  File "./docker/ext_packages/install_upstream_python_packages.py", line 295, in <module>
    verify_installation_through_imports()
  File "./docker/ext_packages/install_upstream_python_packages.py", line 279, in verify_installation_through_imports
    from coronary_mesh_convolution import datasets  # type: ignore[import]
  File "***/anaconda3/envs/se3_bi_equ/lib/python3.8/site-packages/coronary_mesh_convolution/datasets.py", line 1, in <module>
    import torch_geometric
  File "***/anaconda3/envs/se3_bi_equ/lib/python3.8/site-packages/torch_geometric/__init__.py", line 5, in <module>
    from .isinstance import is_torch_instance
  File "***//anaconda3/envs/se3_bi_equ/lib/python3.8/site-packages/torch_geometric/isinstance.py", line 8, in <module>
    import torch._dynamo
  File "***//anaconda3/envs/se3_bi_equ/lib/python3.8/site-packages/torch/_dynamo/__init__.py", line 1, in <module>
    from . import allowed_functions, convert_frame, eval_frame, resume_execution
  File "***/anaconda3/envs/se3_bi_equ/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 29, in <module>
    from .output_graph import OutputGraph
  File "***/anaconda3/envs/se3_bi_equ/lib/python3.8/site-packages/torch/_dynamo/output_graph.py", line 23, in <module>
    from . import config, logging as torchdynamo_logging, variables
  File "***/anaconda3/envs/se3_bi_equ/lib/python3.8/site-packages/torch/_dynamo/variables/__init__.py", line 45, in <module>
    from .torch import TorchVariable
  File "***/anaconda3/envs/se3_bi_equ/lib/python3.8/site-packages/torch/_dynamo/variables/torch.py", line 106, in <module>
    import transformers
  File "***/anaconda3/envs/se3_bi_equ/lib/python3.8/site-packages/transformers/__init__.py", line 43, in <module>
    from . import dependency_versions_check
  File "***/anaconda3/envs/se3_bi_equ/lib/python3.8/site-packages/transformers/dependency_versions_check.py", line 41, in <module>
    require_version_core(deps[pkg])
  File "***/anaconda3/envs/se3_bi_equ/lib/python3.8/site-packages/transformers/utils/versions.py", line 94, in require_version_core
    return require_version(requirement, hint)
  File "***/zxp/anaconda3/envs/se3_bi_equ/lib/python3.8/site-packages/transformers/utils/versions.py", line 85, in require_version
    if want_ver is not None and not ops[op](version.parse(got_ver), version.parse(want_ver)):
  File "***/anaconda3/envs/se3_bi_equ/lib/python3.8/site-packages/packaging/version.py", line 54, in parse
    return Version(version)
  File "***/anaconda3/envs/se3_bi_equ/lib/python3.8/site-packages/packaging/version.py", line 200, in __init__
    raise InvalidVersion(f"Invalid version: '{version}'")
packaging.version.InvalidVersion: Invalid version: '0.10.1,<0.11'
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "***/anaconda3/envs/se3_bi_equ/lib/python3.8/logging/__init__.py", line 2126, in shutdown
    h.flush()
  File "***/anaconda3/envs/se3_bi_equ/lib/python3.8/site-packages/absl/logging/__init__.py", line 872, in flush
    self.stream.flush()
AttributeError: 'NoneType' object has no attribute 'flush'
```

Do you have any suggestions? Or it would be nice to add instructions for installing the GATr using pip.

Best,
Xp

**Comment by ZXP-S-works** [comment]
NVM, I installed GATr without Docker.

Essentially, the package needs to install cudatoolkit and its compatible pytorch. The requirements are in \docker\requirements.txt. Install all the requirements, even for the SE3-transformer's. Then follow the instructions in the \docker\Dockerfile by running it in the terminal. Eventually, GATr is ready to go.

Best,
Xp

**Comment by sbehrend-qc** [comment]
No follow-up, closing for now.

Thanks again for reaching out.
